# Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

title: "OCI CPE"
description: "OCI CPE with Simulated Data Center"
informationalText: "This stack deploys a Customer Premisses Equipment (CPE) on OCI, simulating a on-prem or hybrid/other cloud implementation to connect to OCI workloads."
schemaVersion: 1.1.0
version: "20190304"

source:
  type: quickstart

locale: "en"
variableGroups:
  - title: "Basic Hidden"
    variables:
    - tenancy_ocid
    - region
    - user_ocid
    - fingerprint
    - private_key_path
    visible: false

  - title: "General Configuration"
    variables:
    - app_name
    - compartment_ocid

  - title: "OCI Resources Existent VCN"
    variables:
    - existent_oci_vcn_compartment_ocid
    - existent_oci_vcn_ocid

  - title: "SSH Key Configuration for all Instances"
    variables:
    - generate_public_ssh_key
    - public_ssh_key

  - title: "CPE Compute Configuration"
    variables:
    - cpe_instance_shape
    - cpe_visibility
    - cpe_vendor

  - title: "Example LDAP Server Compute Configuration"
    variables:
    - ldap_instance_shape
    - ldap_instance_visibility

  - title: "Bastion Configuration"
    variables:
    - create_bastion_subnet
    - bastion_visibility
    visible: false

  - title: "Tagging"
    variables:
    - tag_values

  - title: "Extras Hidden"
    variables:
      - instance_private_key
    visible: false

  - title: "Extras Hidden - CPE"
    variables:
      - extra_security_list_name_for_cpe
      - cpe_compartment_description
      - create_new_compartment_for_cpe
      - cpe_image_operating_system
      - cpe_image_operating_system_version
      - cpe_instance_boot_volume_size_in_gbs
      - cpe_instance_count
    visible: false

  - title: "Extras Hidden - LDAP"
    variables:
      - ldap_compartment_description
      - create_new_compartment_for_ldap
      - ldap_image_operating_system
      - ldap_image_operating_system_version
      - ldap_instance_boot_volume_size_in_gbs
    visible: false

  - title: "Hidden CPE Network"
    variables:
      - create_new_vcn
      - create_subnets
      - existent_cpe_subnet_ocid
      - existent_private_subnet_ocid
      - existent_public_subnet_ocid
      - existent_vcn_compartment_ocid
      - existent_vcn_ocid
      - ipv6private_cidr_blocks
      - is_ipv6enabled
      - vcn_cidr_blocks
    visible: false

variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "The compartment in which to create compute instance(s)"
    required: true

  app_name:
    type: string
    title: "Name Prefix"
    required: true
    description: "Prefix to identify the resources that will be created"

  generate_public_ssh_key:
    type: boolean
    title: "Auto generate public ssh key?"
    required: true
    # visible:
    #   and:
    #     - create_new_oke_cluster
    #     - show_advanced

  public_ssh_key:
    type: oci:core:ssh:publickey
    title: "Import your own SSH public key"
    additionalProps:
      allowMultiple: true
    required: false
    pattern: "((^(ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)(,((ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)*$"
    visible:
      and:
        # - and:
        #   - create_new_oke_cluster
        #   - show_advanced
        - not:
          - generate_public_ssh_key

  existent_oci_vcn_compartment_ocid:
    type: oci:identity:compartment:id
    title: "Existent VCN Compartment"
    required: true
    default: compartment_ocid
    visible: true

  existent_oci_vcn_ocid:
    type: oci:core:vcn:id
    title: "Existent VCN with OCI Resources (e.g.: WebLogic on OCI, ATP, etc) to be connected to the CPE"
    required: true
    dependsOn:
        compartmentId: compartment_ocid

  cpe_instance_shape:
    type: oci:core:instanceshapewithflex:name
    title: "Select a flex or fixed shape for the CPE compute instances"
    required: true
    dependsOn:
      compartmentId: compartment_ocid
    # visible:
    #   and:
    #     - create_new_oke_cluster
    #     - show_advanced

  cpe_visibility:
    type: enum
    enum:
    - "Public"
    title: "CPE will be hosted in public or private subnet(s)"
    required: true

  cpe_vendor:
    type: enum
    enum:
    - "Libreswan"
    title: "Enter the CPE vendor to be used. Currently only Libreswan is supported."
    required: true

  ldap_instance_shape:
    type: oci:core:instanceshapewithflex:name
    title: "Select a flex or fixed shape for the Example LDAP Server compute instance"
    required: true
    dependsOn:
      compartmentId: compartment_ocid

  ldap_instance_visibility:
    type: enum
    enum:
    - "Private"
    title: "LDAP will be hosted in public or private subnet(s)"
    required: true

  create_bastion_subnet:
    type: boolean
    title: "Creates a new Bastion Subnet."
    required: true

  bastion_visibility:
    type: enum
    enum:
    - "Private"
    - "Public"
    title: "Bastion will be hosted in public or private subnet(s)"
    required: true

  tag_values:
    type: oci:identity:tag:value
    title: Tag Resources
    required: false
    visible: show_advanced
    dependsOn:
      compartmentId: compartment_ocid

outputGroups:
  - title: Deployment Info
    outputs:
      - deploy_id
      - stack_version

  - title: Passwords and Keys
    outputs:
      - generated_private_key_pem

  - title: Comments
    outputs:
      - comments

  - title: Dev Notes
    outputs:
      - dev

outputs:
  deploy_id:
    type: string
    title: "Deployment Id"
    visible: true

  stack_version:
    type: string
    title: Stack Version
    displayText: Stack Version deployed
    visible: true

  generated_private_key_pem:
    type: string
    title: Generated Private Key
    displayText: Generated Private Key

  comments:
    type: string
    title: Comments
    displayText: Comments
    visible: true

  dev:
    type: string
    title: dev
    displayText: dev note from Oracle Developers
    visible: true

  sensitive_comments_local_tf:
    type: string
    title: kubeconfig
    displayText: Instructions to get sensitive outputs on local Terraform. Not used by ORM
    visible: false
