#cloud-config

packages:
  - libreswan
  - frr

write_files:
  - path: "/etc/ipsec.d/oci-ipsec.conf"
    permissions: "0644"
    content: |
      conn ipsec-tunnel-0
          left=$cpe_local_ip
          leftid=$cpe_public_ip # See preceding note about 1-1 NAT device
          right=$oci_headend1
          authby=secret
          leftsubnet=0.0.0.0/0
          rightsubnet=0.0.0.0/0
          auto=start
          mark=5/0xffffffff # Needs to be unique across all tunnels
          vti-interface=vti1
          vti-routing=no
          ikev2=no # To use IKEv2, change to ikev2=insist
          ike=aes_cbc256-sha2_384;modp1536
          phase2alg=aes_gcm256;modp1536
          encapsulation=yes
          ikelifetime=28800s
          salifetime=3600s
      conn ipsec-tunnel-1
          left=$cpe_local_ip
          leftid=$cpe_public_ip # See preceding note about 1-1 NAT device
          right=$oci_headend2
          authby=secret
          leftsubnet=0.0.0.0/0
          rightsubnet=0.0.0.0/0
          auto=start
          mark=6/0xffffffff # Needs to be unique across all tunnels
          vti-interface=vti2
          vti-routing=no
          ikev2=no # To use IKEv2, change to ikev2=insist
          ike=aes_cbc256-sha2_384;modp1536
          phase2alg=aes_gcm256;modp1536
          encapsulation=yes
          ikelifetime=28800s
          salifetime=3600s
  - path: "/etc/ipsec.d/oci-ipsec.secrets"
    permissions: "0644"
    content: |
      $cpe_public_ip $oci_headend1: PSK "${shared_secret_psk}"
      $cpe_public_ip $oci_headend2: PSK "${shared_secret_psk}"

runcmd:
  # Configure firewall
  - echo "Configuring ports..."
  - firewall-offline-cmd --add-port=500/udp
  - firewall-offline-cmd --add-port=4500/udp
  - systemctl restart firewalld
  # IP Forwarding
  - echo "Configuring IP Forwarding..."
  - sysctl -w net.ipv4.ip_forward=1
  - sysctl -w net.ipv4.conf.all.accept_redirects=0
  - sysctl -w net.ipv4.conf.all.send_redirects=0
  - sysctl -w net.ipv4.conf.default.send_redirects=0
  - sysctl -w net.ipv4.conf.ens3.send_redirects=0
  - sysctl -w net.ipv4.conf.default.accept_redirects=0
  - sysctl -w net.ipv4.conf.ens3.accept_redirects=0
  - sysctl -p

final_message: "The system is finally up, after $UPTIME seconds"
output: {all: '| tee -a /root/cloud-init-output.log'}